management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans

server:
  port: 8060

spring:
  ai:
    mcp:
      server:
        name: k8s-mcp-server-spring-ai
        version: 0.0.1
        type: ASYNC  
        enabled: true
        instructions: "This reactive server provides kubernetes information tools and resources"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true